baseURL = "/"
languageCode = "he-IL"
title = "Dramakings"
theme = "hugo-lithium-theme"
[taxonomies]
  tag = "tags"
  
[[menu.main]]
    name = "קצת עליי"
    url = "/about/"
[[menu.main]]
    name = "פיילוטים"
    url = ""
[[menu.main]]
    name = "ספרים שקראתי"
    url = ""

  
[params]
    customCSS = [ "custom.css" ]

    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


