baseURL = "/"
languageCode = "he-IL"
title = "Dramakings"
theme = "hugo-lithium-theme"

[taxonomies]
  tag = "tags"
  category = "categories"
  
[[menu.main]]
    name = "About"
    url = "/page/about/"
[[menu.main]]
    name = "#Tags"
    url = "/page/tags/"
[[menu.main]]
    name = "ספריה"
    url = "/page/books/"
[[menu.main]]
    name = "בלוג"
    url = "/"

  
[params]
    customCSS = [ "custom.css" ]

    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


