baseURL = "/"
languageCode = "he-IL"
title = "Dramakings"
theme = "hugo-lithium-theme"
[taxonomies]
  tag = "tags"
  
[[menu.main]]
    name = "קצת עליי"
    url = "/page/about/"
[[menu.main]]
    name = "מחשבות על פרק#"
    url = "/page/episodes/"
[[menu.main]]
    name = "ספריה"
    url = "/page/books/"

  
[params]
    customCSS = [ "custom.css" ]

    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


